// BigBubbleMuff — the DK circuit model against ngspice-47 (tests/data/spice).
// Copyright (C) 2026  BigBubbleMuff contributors. SPDX-License-Identifier: MIT
//
// The goldens come from docs/spice/bigmuff.cir with the engine's exact device subset
// (docs/spice/models-em.lib), regenerated by tools/spice/gen_goldens.sh. They are the
// ground truth: the engine is right when it agrees with them.
#include "test.h"

#include "dsp/circuit/BigMuffCircuit.h"

#include <chrono>
#include <cmath>
#include <complex>
#include <cstdio>
#include <fstream>
#include <map>
#include <numbers>
#include <sstream>
#include <string>
#include <vector>

using bbm::circuit::BigMuffCircuit;
using bbm::circuit::Knobs;

namespace {

constexpr double kGoldenRate = 192000.0; // gen_goldens.sh FS

std::string dataPath(const std::string &name) {
  return std::string(BBM_TEST_DATA) + "/spice/" + name;
}

// "name,value" rows after a header line.
std::map<std::string, double> readCsvMap(const std::string &name) {
  std::map<std::string, double> m;
  std::ifstream f(dataPath(name));
  std::string line;
  std::getline(f, line);
  while (std::getline(f, line)) {
    const auto comma = line.find(',');
    if (comma != std::string::npos)
      m[line.substr(0, comma)] = std::stod(line.substr(comma + 1));
  }
  return m;
}

struct Curve {
  std::vector<double> hz, db;
};
Curve readAc(const std::string &name) {
  Curve c;
  std::ifstream f(dataPath(name));
  std::string line;
  std::getline(f, line);
  while (std::getline(f, line)) {
    const auto comma = line.find(',');
    if (comma == std::string::npos)
      continue;
    c.hz.push_back(std::stod(line.substr(0, comma)));
    c.db.push_back(std::stod(line.substr(comma + 1)));
  }
  return c;
}
// dB at `hz`, linear in log-frequency between the golden's points.
double interpDb(const Curve &c, double hz) {
  for (std::size_t k = 1; k < c.hz.size(); ++k)
    if (c.hz[k] >= hz) {
      const double t = (std::log(hz) - std::log(c.hz[k - 1])) /
                       (std::log(c.hz[k]) - std::log(c.hz[k - 1]));
      return c.db[k - 1] + t * (c.db[k] - c.db[k - 1]);
    }
  return c.db.back();
}

// A transient golden: the header's stimulus and the v(out) column.
struct Tran {
  double sus = 0, tone = 0, vol = 0;
  double amp = 0, hz = 0, damping = 0;
  std::vector<double> out;
};
Tran readTran(const std::string &name) {
  Tran t;
  std::ifstream f(dataPath(name));
  std::string header;
  std::getline(f, header);
  const auto field = [&header](const std::string &key) {
    const auto at = header.find(key + "=");
    return at == std::string::npos ? std::string() : header.substr(at + key.size() + 1);
  };
  t.sus = std::stod(field("sus"));
  t.tone = std::stod(field("tone"));
  t.vol = std::stod(field("vol"));
  // src=SIN(0 amp hz [delay damping])
  std::istringstream src(field("src").substr(4));
  double offset = 0, delay = 0;
  src >> offset >> t.amp >> t.hz;
  if (!(src >> delay >> t.damping))
    t.damping = 0;
  std::string line;
  while (std::getline(f, line))
    if (!line.empty())
      t.out.push_back(std::stod(line));
  return t;
}

BigMuffCircuit &preparedCircuit(const Knobs &k, double fs = kGoldenRate) {
  static BigMuffCircuit c; // ~20 KB: keep it off the test's stack
  c.setKnobs(k);
  CHECK(c.prepare(fs));
  return c;
}

} // namespace

TEST_CASE("DK circuit", "DC operating point matches ngspice within 1 mV per node") {
  const BigMuffCircuit &c = preparedCircuit(Knobs{}); // the deck's defaults
  const auto golden = readCsvMap("op_em.csv");
  CHECK(golden.size() == 24);
  const char *names[] = {"n1", "b4", "c4",  "e4",  "s3", "s2", "s1", "n5",  "b3",
                         "c3", "e3", "d3n", "n13", "b2", "c2", "e2", "d2n", "t3",
                         "t2", "t1", "b1",  "c1",  "e1", "v3", "out"};
  double worst = 0.0;
  for (std::size_t n = 0; n < bbm::circuit::kNodes; ++n) {
    const auto it = golden.find(names[n]);
    if (it == golden.end())
      continue; // n1 is not in the golden (it sits at 0 V through R2)
    const double err = std::fabs(c.dcNodes()[n] - it->second);
    worst = std::max(worst, err);
    CHECK_MSG(err < 1e-3, std::string(names[n]) + " = " + std::to_string(c.dcNodes()[n]) +
                              ", ngspice " + std::to_string(it->second));
  }
  bbmtest::log("DC: worst node error " + std::to_string(worst * 1e3) + " mV");
}

TEST_CASE("DK circuit",
          "the DC operating point is a fixed point of the discrete system") {
  BigMuffCircuit &c = preparedCircuit(Knobs{1.0, 0.5, 1.0});
  double worst = 0.0;
  for (int n = 0; n < 48000; ++n)
    worst = std::max(worst, std::fabs(c.process(0.0)));
  CHECK_MSG(worst < 1e-9, "silent input drifted to " + std::to_string(worst) + " V");
  CHECK(c.stats().rejected == 0);
  CHECK(c.stats().unconverged == 0);
}

TEST_CASE("DK circuit",
          "small-signal response matches ngspice AC within 0.5 dB, 20 Hz-10 kHz") {
  // Nine tones at once (superposition holds at 1e-7 V), each on an exact DFT bin of
  // the 0.1 s analysis window, after 0.3 s to let the coupling capacitors settle.
  const double tones[] = {20, 50, 100, 200, 500, 1000, 2000, 5000, 10000};
  constexpr double kAmp = 1e-7;
  const auto settle = static_cast<int>(0.3 * kGoldenRate);
  const auto window = static_cast<int>(0.1 * kGoldenRate);
  const char *grid[] = {"0", "0.25", "0.5", "0.75", "1"};
  double worst = 0.0;
  std::string worstAt;
  for (const char *s : grid)
    for (const char *t : grid) {
      BigMuffCircuit &c = preparedCircuit(Knobs{std::stod(s), std::stod(t), 1.0});
      const Curve golden = readAc(std::string("ac_s") + s + "_t" + t + ".csv");
      std::vector<std::complex<double>> acc(std::size(tones));
      for (int n = 0; n < settle + window; ++n) {
        const double time = n / kGoldenRate;
        double vin = 0.0;
        for (std::size_t k = 0; k < std::size(tones); ++k)
          vin +=
              kAmp * std::sin(2.0 * std::numbers::pi * tones[k] * time + 0.7 * double(k));
        const double y = c.process(vin);
        if (n >= settle)
          for (std::size_t k = 0; k < std::size(tones); ++k)
            acc[k] += y * std::polar(1.0, -2.0 * std::numbers::pi * tones[k] * time);
      }
      for (std::size_t k = 0; k < std::size(tones); ++k) {
        const double gainDb = 20.0 * std::log10(2.0 * std::abs(acc[k]) / window / kAmp);
        const double err = gainDb - interpDb(golden, tones[k]);
        if (std::fabs(err) > std::fabs(worst)) {
          worst = err;
          worstAt = std::string("sus ") + s + " tone " + t + " at " +
                    std::to_string(int(tones[k])) + " Hz";
        }
        CHECK_MSG(std::fabs(err) < 0.5, std::string("sus ") + s + " tone " + t + " at " +
                                            std::to_string(tones[k]) +
                                            " Hz: " + std::to_string(err) + " dB");
      }
    }
  bbmtest::log("AC: worst error " + std::to_string(worst) + " dB (" + worstAt + ")");
}

namespace {
// RMS of (engine - golden) relative to the golden's RMS, in dB.
double tranErrorDb(const std::string &name, double &peakErr) {
  const Tran g = readTran(name);
  BigMuffCircuit &c = preparedCircuit(Knobs{g.sus, g.tone, g.vol});
  double e2 = 0.0;
  double r2 = 0.0;
  peakErr = 0.0;
  for (std::size_t k = 0; k < g.out.size(); ++k) {
    const double time = double(k) / kGoldenRate;
    const double vin = g.amp * std::exp(-g.damping * time) *
                       std::sin(2.0 * std::numbers::pi * g.hz * time);
    const double d = c.process(vin) - g.out[k];
    e2 += d * d;
    r2 += g.out[k] * g.out[k];
    peakErr = std::max(peakErr, std::fabs(d));
  }
  CHECK(c.stats().rejected == 0);
  return 10.0 * std::log10(e2 / r2);
}
} // namespace

TEST_CASE("DK circuit", "transients match the ngspice EM-model runs") {
  const char *runs[] = {"tran_em_sin1k_a0.01_s0.75.txt", "tran_em_sin1k_a0.1_s0.75.txt",
                        "tran_em_sin1k_a1_s0.75.txt",    "tran_em_sin100_a0.1_s0.txt",
                        "tran_em_sin100_a0.1_s0.5.txt",  "tran_em_sin100_a0.1_s1.txt",
                        "tran_em_pluck196_s0.75.txt"};
  for (const char *r : runs) {
    double peak = 0.0;
    const double db = tranErrorDb(r, peak);
    bbmtest::log(std::string("tran ") + r + ": error " + std::to_string(db) +
                 " dB, peak " + std::to_string(peak * 1e3) + " mV");
    CHECK_MSG(db < -30.0, std::string(r) + ": " + std::to_string(db) + " dB");
  }
}

TEST_CASE("DK circuit", "gap to the full Gummel-Poon models (reported)") {
  for (const char *r : {"tran_gp_sin1k_a0.01_s0.75.txt", "tran_gp_sin1k_a0.1_s0.75.txt",
                        "tran_gp_sin1k_a1_s0.75.txt"}) {
    double peak = 0.0;
    const double db = tranErrorDb(r, peak);
    bbmtest::log(std::string("GP gap ") + r + ": " + std::to_string(db) + " dB, peak " +
                 std::to_string(peak * 1e3) + " mV");
  }
}

TEST_CASE("DK circuit", "solver cost at 4 x 48 kHz (reported)") {
  BigMuffCircuit &c = preparedCircuit(Knobs{0.75, 0.5, 1.0});
  const auto n = static_cast<int>(kGoldenRate);
  double sink = 0.0;
  const auto t0 = std::chrono::steady_clock::now();
  for (int k = 0; k < n; ++k)
    sink += c.process(0.3 * std::sin(2.0 * std::numbers::pi * 196.0 * k / kGoldenRate));
  const double secs =
      std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
  CHECK(std::isfinite(sink));
  char msg[160];
  std::snprintf(msg, sizeof msg,
                "cost: %.1f%% of one core for 1 s of audio at 4x48k, %.2f Newton "
                "iterations/sample, %ld unconverged",
                100.0 * secs, double(c.stats().iterations) / double(c.stats().samples),
                c.stats().unconverged);
  bbmtest::log(msg);
}
