// BigBubbleMuff — build tool: compiles resource files into a C++ source.
// Copyright (C) 2026  BigBubbleMuff contributors. SPDX-License-Identifier: MIT
//
//   embed_resources <out.cpp> <name>=<file> [<name>=<file> ...]
//
// Writes a translation unit defining bbm::findResource() (src/gfx/resources.h)
// over one static array per file. Runs on the build host only; nothing of it is
// linked into the plug-in except its output. The output is written beside the
// target and renamed into place, so an interrupted build never leaves a truncated
// source that looks up to date.
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace {

struct Input {
  std::string name;
  std::vector<unsigned char> bytes;
};

bool readAll(const std::string &path, std::vector<unsigned char> &out) {
  std::error_code ec;
  const std::uintmax_t size = std::filesystem::file_size(path, ec);
  if (ec)
    return false;
  std::ifstream in(path, std::ios::binary);
  if (!in)
    return false;
  out.resize(static_cast<std::size_t>(size));
  // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
  in.read(reinterpret_cast<char *>(out.data()), static_cast<std::streamsize>(size));
  return static_cast<std::uintmax_t>(in.gcount()) == size;
}

// A name is emitted inside a string literal; refuse anything that would need
// escaping rather than escape it.
bool plainName(std::string_view s) {
  if (s.empty())
    return false;
  for (const char c : s) {
    const bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
                    (c >= '0' && c <= '9') || c == '/' || c == '.' || c == '_' ||
                    c == '-';
    if (!ok)
      return false;
  }
  return true;
}

void writeArray(std::ofstream &out, std::size_t index,
                const std::vector<unsigned char> &bytes) {
  static constexpr std::string_view kHex = "0123456789abcdef";
  out << "alignas(16) const unsigned char kData" << index << "[] = {";
  std::string line;
  for (std::size_t i = 0; i < bytes.size(); ++i) {
    if (i % 16 == 0) {
      out << line << "\n  ";
      line.clear();
    }
    const unsigned char b = bytes[i];
    line += "0x";
    line += kHex[b >> 4U];
    line += kHex[b & 0xFU];
    line += ',';
  }
  // An empty file still needs one element to be a valid array.
  out << line << (bytes.empty() ? "0" : "") << "};\n";
}

} // namespace

int main(int argc, char **argv) {
  const std::span<char *> args(argv, static_cast<std::size_t>(argc));
  if (args.size() < 3) {
    std::fputs("usage: embed_resources <out.cpp> <name>=<file>...\n", stderr);
    return 2;
  }

  std::vector<Input> inputs;
  for (std::size_t i = 2; i < args.size(); ++i) {
    const std::string arg(args[i]);
    const std::size_t eq = arg.find('=');
    if (eq == std::string::npos || !plainName(std::string_view(arg).substr(0, eq))) {
      std::fprintf(stderr, "embed_resources: bad argument '%s'\n", arg.c_str());
      return 2;
    }
    Input in{arg.substr(0, eq), {}};
    if (!readAll(arg.substr(eq + 1), in.bytes)) {
      std::fprintf(stderr, "embed_resources: cannot read '%s'\n", arg.c_str() + eq + 1);
      return 1;
    }
    inputs.push_back(std::move(in));
  }

  const std::filesystem::path target(args[1]);
  std::filesystem::path temp = target;
  temp += ".tmp";
  {
    std::ofstream out(temp, std::ios::binary | std::ios::trunc);
    if (!out) {
      std::fprintf(stderr, "embed_resources: cannot write '%s'\n", temp.c_str());
      return 1;
    }
    out << "// Generated by tools/embed_resources.cpp. Do not edit.\n"
           "#include \"gfx/resources.h\"\n\n"
           "#include <array>\n\n"
           "namespace bbm {\nnamespace {\n";
    for (std::size_t i = 0; i < inputs.size(); ++i)
      writeArray(out, i, inputs[i].bytes);
    out << "\nstruct Entry {\n  std::string_view name;\n"
           "  std::span<const unsigned char> bytes;\n};\n\n"
        << "const std::array<Entry, " << inputs.size() << "> kEntries{{\n";
    for (std::size_t i = 0; i < inputs.size(); ++i)
      out << "    {\"" << inputs[i].name << "\", {kData" << i << ", "
          << inputs[i].bytes.size() << "}},\n";
    out << "}};\n} // namespace\n\n"
           "std::span<const unsigned char> findResource(std::string_view name) "
           "noexcept {\n"
           "  for (const Entry &e : kEntries)\n"
           "    if (e.name == name)\n"
           "      return e.bytes;\n"
           "  return {};\n}\n\n} // namespace bbm\n";
    if (!out.flush()) {
      std::fprintf(stderr, "embed_resources: write failed for '%s'\n", temp.c_str());
      return 1;
    }
  }
  std::error_code ec;
  std::filesystem::rename(temp, target, ec);
  if (ec) {
    std::fprintf(stderr, "embed_resources: cannot rename to '%s'\n", target.c_str());
    return 1;
  }
  return 0;
}
